apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity
  labels:
    app: udacity
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udacity
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udacity
    spec:
      containers:
        - image: bkocis/udacity
          imagePullPolicy: Always
          name: udacity
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: udacity
  labels:
    app: udacity
spec:
  type: LoadBalancer
  selector:
    app: udacity
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30000
      protocol: TCP
